### ISSUE TITLE
Add JSON generation

### ISSUE THREAD

**Issue by danellecline** [mbari-org/pypam-based-processing#5]
Add JSON generation to simplify the steps for processing with pypam.   

Reference repo: 
[https://github.com/mbari-org/soundscape-wavdata](https://github.com/mbari-org/soundscape-wavdata)
[https://github.com/ioos/soundcoop/](https://github.com/ioos/soundcoop/)
 

```[tasklist]
### Tasks
- [x] Create branch for this work (jsongen)
- [x] Copy modules from soundscape-wavdata into appropriate modules
- [ ] Add entrypoint for calling the metadata generation
- [ ] Add pytest
- [ ] Add simple notebook to demonstrate local JSON generation
```

**Comment by danellecline** [comment]
@ryjombari, just FYI, in case you want to follow along.

**Comment by danellecline** [comment]
@carueda - where would you like me to put the modules? It should be different than the .nc metadata in metadata to avoid confusion.

**Comment by ryjombari** [comment]
Thanks for the jumpstart @danellecline!

**Comment by ryjombari** [comment]
Relaying a thought from communications with Samara @ NOAA: Tooling this demonstration to gather metadata and read data directly from the Google Cloud Platform would pave the way for PBP to be the engine for a lot of NOAA passive acoustic data.  If I understand, MinIO can be used to move data from GCP to the processing instance, and PBP can move to using MinIO?  How about the gathering of file metadata?

**Comment by danellecline** [comment]
Thanks @ryjombari. @carueda I'm' wondering if 1) does Minio replace boto3, or do they stand side-by-side, and 2) does boto3 support GCP.  I know that minio is S3 compliant and can be used for both local and cloud storage operations - I am using it now for video processing pipelines successfully.

**Comment by carueda** [comment]
I haven't looked into minio with enough detail to tell for sure, but I think it supports AWS, GCP, and probably others. If so, we could replace the boto3 dependency with minio and adjust the appropriate places dealing with file downloads/uploads (s3 and gs URIs)

**Comment by carueda** [comment]
As part of #6, I note that Minio seems to only be for s3 compliant endpoints, and I started using the `google-cloud-storage` package for handling `gs://`.
